### ISSUE TITLE
Map scrolling button doesn't show

### ISSUE THREAD

**Issue by TogrulM** [thurban/plugin_weathermap#10]
Hello,
I have installed this weathermap (0.98a dev) on the cacti 1.2.12 version. Plugin installed and working but I have problem with scrolling with big map sizes scrolling button doesn't show, only with using mouse scrolling up and down can fulfill but right and left can not execute.
Could you please help me with issue?
Thank you in advance.

**Comment by jamesbtate** [comment]
As a workaround, if your mouse has "middle-click" where you click with the scroll wheel: Middle click on the page and then you can drag the mouse any direction to scroll that way.

Another workaround: right-click any part of the blank background and choose the option to "view image" or "open image in new tab." Then the scroll bars should appear.

I'd guess some minor CSS tweak would fix this but I don't have time to look at it now.

**Comment by TogrulM** [comment]
> 
> 
> As a workaround, if your mouse has "middle-click" where you click with the scroll wheel: Middle click on the page and then you can drag the mouse any direction to scroll that way.
> 
> Another workaround: right-click any part of the blank background and choose the option to "view image" or "open image in new tab." Then the scroll bars should appear.
> 
> I'd guess some minor CSS tweak would fix this but I don't have time to look at it now.

Thank you for your suggestions.
Mouse "middle-click" also useable for up and down.
Right-click and "view image" only help for viewing the whole map as an image, but with this, I can not click a link and open accordingly graph.

**Comment by oijkn** [comment]
I think this issue can be closed.

**Comment by TogrulM** [comment]
Thank you support. Issue fixed.
