### ISSUE TITLE
logs weathermap 

### ISSUE THREAD

**Issue by Bochi75** [thurban/plugin_weathermap#109]
Hello Team,

I installed plugins weathermap versoin 1.0, I can see these logs:

2023-03-06 09:50:32 - WEATHERMAP WARNING: Unable to move BACKGROUND

Someone can explain what it is about ? 

OS: Ubuntu 20.04
Cacti version: 1.2.24
Plugin Weathermap version: 1.0

Regards,

**Comment by TheWitness** [comment]
The weathermap plugin attempts to move the Image files pointed to in the config files to the new locations.  There may be a permission error preventing this.
