### ISSUE TITLE
Weathermap config file corruption

### ISSUE THREAD

**Issue by jakeybrakey** [thurban/plugin_weathermap#110]
Fresh Ubuntu 5.15.0-67 and weathermap current development version on new Cacti 1.2.24, and migrated install from 0.8.8h. The weathermap config files upon adding or using web editor often or frequently get cleared of all contents, or cleared leaving only 1 line (the BACKGROUND statement line, even if it is commented). I made them read-only and then added them, and only edit with text editor as workaround.

**Comment by TheWitness** [comment]
Do you have anything in your Cacti log?  Also, does WeatherMap have the ability to move the IMAGES from where they are currently located to the new location?

**Comment by mahavirjain98** [comment]
I also had similar issues of config file getting blanked out once the config is made active, mine got solved post moving all the background images in background directory, image files in images directory and correcting the paths in config file.
Just check if it solves for you too.

**Comment by TheWitness** [comment]
@jakeybrakey, please follow @mahavirjain98 instructions.  Going to close this as a known upgrade issue.  I have updated the readme to add a few warnings.  I think I'll leave it there.
