### ISSUE TITLE
Unable to install the plugin

### ISSUE THREAD

**Issue by darkness4773** [thurban/plugin_weathermap#115]
Hi all,

When i try to install the weathermap plugin new version, i'm facing an error message and i can't enable it

I put the plugin folder in Cacti/plugins
I rename it "weathermap", in lowercase
I went to Cacti \ settings\plugins
I saw the plugin available so i clicked on the INSTALL button ==> error message below:
    Error:	500 Internal Server Error
    Reason:	The response to the last action was unexpected.
 I refreshed the page and the plugins seemed installed
So I clicked on the ENABLE button and i got a blank page

I installed few plugins in Cacti and i never had this

 the weathermap folder and its files have the right permissions (the sames as the previous version)

so i don't undrestant why :(

**Comment by TheWitness** [comment]
Minimum Cacti version should be 1.2.24++.  Sorry about that.  Please upgrade.

**Comment by darkness4773** [comment]
Hi 
I upgraded to the version 1.2.24 but i still have the issue.

Action Failed
Sorry, we could not process your last action.
Error:
500 Internal Server Error
Reason:
The response to the last action was unexpected.

**Comment by TheWitness** [comment]
What's your PHP version?

**Comment by darkness4773** [comment]
old version 5.4.16

**Comment by TheWitness** [comment]
Yea, our bad.  You should update PHP to 8.2.  If you are using RHEL7 or variant, using the REMI repo you can achieve with Zero downtime.  He's done a great job with them and he also runs Cacti.  So, that helps too.  With 1.2.24, we accidentally introduced a dependency on PHP >= 7.x.

**Comment by darkness4773** [comment]
Hi

Ok
I'm going to upgrade all

thanks
