### ISSUE TITLE
Weathermap groups doesn't allow users to see map

### ISSUE THREAD

**Issue by manel1984** [thurban/plugin_weathermap#125]
Hello,

I'm currently using cacti 1.2.25 and weathermap 1.1.

When a group is allowed to view a map, all the users in that group cannot see it.

What I see is:

Group is added in weathermap_auth with a minus value (that's correct), but the last query for allow is
SELECT mapid FROM weathermap_auth WHERE userid = 'xxx' AND mapid = 'xx' this userid doesn't exist in that table.

Would you mind helping me?

Manel Pérez

**Comment by TheWitness** [comment]
Are you using the tag or the develop branch?

**Comment by manel1984** [comment]
Develop branch

**Comment by TheWitness** [comment]
Can you provide a file/line number?

**Comment by TheWitness** [comment]
I may also require a DB dump via Email of course.

**Comment by TheWitness** [comment]
No feedback.

**Comment by manel1984** [comment]
Sorry I thought I had answered, It's not possible to send the db. Let me do a fresh install and try to reproduce it
