### ISSUE TITLE
Cacti 1.2.25 and Weathermap 0.98a

### ISSUE THREAD

**Issue by alcatron** [thurban/plugin_weathermap#131]
Just updated from Cacti 1.2.23 to 1.2.25 and all of a sudden i see this in the logs.. however it doesnt affect weathermap operations.. is there a way to clear this? Running Weathermap 0.98a

PLUGIN WARNING: Plugin 'weathermap' is attempting to call 'api_plugin_register_realm' improperly in function 'weathermap_config_arrays'

**Comment by TheWitness** [comment]
My recommendation would be to get yourself onto the latest Cacti development version here.  It's located here:

https://github.com/cacti/plugin_weathermap

There are still a few bugs and issues.  So, review the issue list and README.md carefully before upgrading.  Lot's of people are using it.  Just need some time to get to the open bugs.

**Comment by alcatron** [comment]
Hi Witness, I have tried the latest branch 1.1 and it appears to be working ok.

However can I make some recommendations for you so that the hovering is working good over links because right now in 1.11 it is squeezed way out the graph and doesn't seem sized properly like previous versions.

In /usr/share/cacti/plugins/weathermap/js/weathermap.js I also had to modify the following so the hover sizing is right 

_ui.tooltip.css('min-width', '200px');_ 

The previous value was 600 which didn't really suit.

Also the hover sizing of the graphs made them too squeezed/small, I found these settings the most optimal and nicely sized hover graphs.

![2023-12-04 18 29 00](https://github.com/Cacti/plugin_weathermap/assets/27321443/7abf98f0-e2a8-4c8c-93f7-7e718ea6a9d5)

**Comment by TheWitness** [comment]
We welcome pull requests.  Please create one.

**Comment by alcatron** [comment]
sorry, im not really a developer so im not sure what you mean by pull request, but i did try to go to the option of a pull request and its just greyed out for me and nothing else to select so im not sure what im exactly doing.

Im just trying to contribute to make the newer version better.

**Comment by TheWitness** [comment]
It's not the complicated.  Click on the 'fork' word in the top right, and GitHub will make a copy under your account.  Then go to the files in the location and Edit the file that needs to be changed.  Once you are done making changes, a button should show up to "Contribute" or "Create Pull Request" where you can contribute your minor changes back to the Cacti version of the Repo.  Give it a shot.

**Comment by alcatron** [comment]
ok thanks, i worked it out should see it.

What about inside cacti weathermap tab options, what file is that kept in? (one i screenshot)

**Comment by TheWitness** [comment]
Usually the setup.php.  look for config_settings hook.

**Comment by alcatron** [comment]
ok i found it in setup.php in weathermap plugin.. when you make the changes manually in the cacti tab "configuration > settings> Weathermap", where are they changes actually saved in, what file?

**Comment by TheWitness** [comment]
They get saved to the settings table in MySQL/MariaDB.

**Comment by TheWitness** [comment]
Nothing left to do I think.  Pull requests are always welcome.
