### ISSUE TITLE
weathermap CLI broken

### ISSUE THREAD

**Issue by bsyd** [thurban/plugin_weathermap#134]
The weathermap CLI is currently not usable.
```
[root@cacti weathermap]# php weathermap
PHP Fatal error:  Uncaught Error: Call to undefined function cacti_sizeof() in /usr/share/cacti/plugins/weathermap/weathermap:65
Stack trace:
#0 {main}
  thrown in /usr/share/cacti/plugins/weathermap/weathermap on line 65

```

Adding the following line fixes the execution : 
`require_once('../../include/global.php');
`

Here is the patch.
[weathermap.patch](https://github.com/Cacti/plugin_weathermap/files/13600242/weathermap.patch)

**Comment by TheWitness** [comment]
Thanks for that.  Better to include cli_check.php.  can you do a pull request?

**Comment by bsyd** [comment]
Here you go. #135
