### ISSUE TITLE
Bug Weathermap - Map Style can't change Link Labels to Bits/Sec

### ISSUE THREAD

**Issue by Umpheakdeys** [thurban/plugin_weathermap#141]
Hello,

I have a problem with Weathermap can't change map style link labels to Bits/Sec.

I hope to fix this problem soon.

Thank you

![Image_20240123130050](https://github.com/Cacti/plugin_weathermap/assets/86238637/7998272e-dec3-48b0-ab12-70558299eeeb)

**Comment by TheWitness** [comment]
Worked for me perfectly.  Any errors in the Cacti log?

**Comment by Umpheakdeys** [comment]
> Worked for me perfectly. Any errors in the Cacti log?

It does not work for me when I change from Percentage to Bits/Sec. After refreshing the Weathermap editor it still Percentage.

![image](https://github.com/Cacti/plugin_weathermap/assets/86238637/d6c3d5c2-015a-41df-8c99-5fb998483c79)

**Comment by Umpheakdeys** [comment]
https://github.com/Cacti/plugin_weathermap/assets/86238637/576d89c9-cda5-44f6-9db2-56cec39bb2bb

**Comment by TheWitness** [comment]
Does the web server have write access to the config file?

**Comment by Umpheakdeys** [comment]
> Does the web server have write access to the config file?

Yes, my web server can write access normally.

![image](https://github.com/Cacti/plugin_weathermap/assets/86238637/17a7c49a-4dfc-4412-bf86-be14ca5f6134)

**Comment by Phallideth** [comment]
Hi, I am having the same issue. How to fix it?

**Comment by Umpheakdeys** [comment]
> Hi, I am having the same issue. How to fix it?

we are still waiting for a new update for the new version hop that can fix this problem.

**Comment by kmorales026** [comment]
Hi, I am having the same issue!!!, who know who to fix it??, thanks!! 
Cacti Version 1.2.26

*workaround* I added HTMLSTYLE overlib and **BWLABEL bits** under regular LINKs section, its seem like global options is not taken options.*

**Comment by TheWitness** [comment]
I'm just getting back to work on Cacti guys.  Will need some time.  Lot's of plugins and then Cacti too.

**Comment by ZacharyPuls** [comment]
It looks like this issue is present when creating a a new map via the UI, it doesn't generate a template link. You can work around this by manually adding a template link and setting the BWLABEL option:

```
# TEMPLATE-only LINKs:
LINK DEFAULT
        WIDTH 5
        ARROWSTYLE compact
        BWLABEL bits
        BANDWIDTH 10000M
```

**Comment by TheWitness** [comment]
Thanks for pointing that out @ZacharyPuls!  Let me look into that.

**Comment by TheWitness** [comment]
@ZacharyPuls, after a cursory review of the code, there is no where where it sets or saves the default's.  Has this worked in the past where the editor had no defaults?

**Comment by TheWitness** [comment]
This is resolved now.  Please test the develop version.

**Comment by Umpheakdeys** [comment]
> This is resolved now. Please test the develop version.

Now this problem has been resolved thank you for your help.
