### ISSUE TITLE
Missing link to the page "Weathermap Editor" to create new weathermap

### ISSUE THREAD

**Issue by nbz6** [thurban/plugin_weathermap#144]
# Describe the bug

Weathermap 1.2 is missing link to create new weathermap from scratch or a copy of a previous weathermap like it was in Weathermap 0.98
This page is the Weathermap Editor : /plugins/weathermap/weathermap-cacti-plugin-editor.php

## To Reproduce

1. Go to 'Console' > 'Management' > 'Weathermap'

2. Click on '+'

3. On the Weathermap Management Page, you can't create a new weathermap.
Only already created config file are present, impossible to create a new weathermap and no link to the Editor Page.

## Expected behavior

We should be able to create a new weathermap from scratch as it was in the previous version.
The page still exist but there is no link to it, we have to open it manually : 
/plugins/weathermap/weathermap-cacti-plugin-editor.php

Weathermap plugin both "Management Page" and "Editor Page" to exist, but there is not link to the Editor page anymore.

Alternatively this "Weathermap Editor" page could be present here too :

1. Go to 'Console' > 'Create'
2. It could be present a 'New Weathermap' option

## Screenshots

Weathermap 0.98 : 
![image](https://github.com/Cacti/plugin_weathermap/assets/4399512/c2a1939d-e3e1-4ca1-88dc-dcc9daf91a95)
"Editor" link open : /plugins/weathermap/weathermap-cacti-plugin-editor.php

Weathermap 1.2 : 
![image](https://github.com/Cacti/plugin_weathermap/assets/4399512/a498f111-4f1d-484c-82c3-ccff6e754fad)
"New map" link open : /plugins/weathermap/weathermap-cacti-plugin-mgmt.php?action=addmap_picker

But it's the Management page, not the Editor page. And still no link to open the Editor page.
The "New Map" here should open /plugins/weathermap/weathermap-cacti-plugin-editor.php instead in a more integrated way inside Cacti and not in a new white page.

## Additionals contexts

In the Management Page, we can't even make a copy of an existing weathermap : 
![image](https://github.com/Cacti/plugin_weathermap/assets/4399512/f985f8f5-0292-48bb-93fa-93689d0b4a1e)

In Console Management Pages the "Weathermap help link" aren't present anymore too : 
Weathermap 0.98 : 
![image](https://github.com/Cacti/plugin_weathermap/assets/4399512/481fbaf2-6531-4997-9c2b-bb92d9e15878)

Weathermap 1.2 : 
![image](https://github.com/Cacti/plugin_weathermap/assets/4399512/62672ce6-4de4-4b65-bb8a-555feb90ba8c)

So here too there is no way to open the Editor page, even if the footer had the correct link.
Even if the "Show Weathermap Help Links" is checked in configuration.

**Comment by TheWitness** [comment]
Set the weathermap_db_version to something like 1.0 and then let weathermap upgrade again:

```sql
UPDATE settings SET value='1.0' WHERE name='weathermap_db_version';
```

**Comment by TheWitness** [comment]
That should get it.
