### ISSUE TITLE
The metrics are misaligned

### ISSUE THREAD

**Issue by oijkn** [thurban/plugin_weathermap#15]
I noticed that the metrics are misaligned on the map, i.e. the values are not in the boxes (see capture).

Cacti: v1.2.16
OS: FreeBSD 12.1 

![image](https://user-images.githubusercontent.com/18188407/103533270-197e6080-4e8d-11eb-8753-51d17dcc45d5.png)

**Comment by howardjones** [comment]
To use angled text, you need to define a freetype font.

**Comment by oijkn** [comment]
> To use angled text, you need to define a freetype font.

How I can set freetype font, please ?

**Comment by howardjones** [comment]
When you looked in the logs for a warning, you saw a WMWARN02, right? "Angled text doesn't work with non-FreeType fonts"

https://network-weathermap.com/manual/0.98/pages/errorcodes.html#WMARN02

**Comment by oijkn** [comment]
@howardjones Thank you for your reply, so I added in my map conf file `FONTDEFINE 10 ./VeraBd.ttf 8` and now all is well aligned :)
