### ISSUE TITLE
Cacti plugin Weathermap 1.1 issue on weathermap-cacti-plugin-mgmt.php

### ISSUE THREAD

**Issue by paroke65** [thurban/plugin_weathermap#150]
2024/06/24 17:37:21 [error] 19281#19281: *1 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function raise_message_javascript() in /opt/nginx/cacti/plugins/weathermap/weathermap-cacti-plugin-mgmt.php:327
Stack trace:
#0 {main}
  thrown in /opt/nginx/cacti/plugins/weathermap/weathermap-cacti-plugin-mgmt.php on line 327" while reading response header from upstream, client: 124.15.14.5, server: cacti, request: "GET /cacti/plugins/weathermap/weathermap-cacti-plugin-mgmt.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm/php-fpm.sock:", host: "124.15.14.52", referrer: "http://124.15.14.52/cacti/plugins.php"

**Comment by TheWitness** [comment]
What Cacti version?

**Comment by paroke65** [comment]
cacti version 1.2.22

**Comment by paroke65** [comment]
I managed to fix the issue : 
it was necessary to modify the permissions for the Weathermap directory

**Comment by paroke65** [comment]
I managed to fix the issue :
it was necessary to modify the permissions for the Weathermap directory
