### ISSUE TITLE
No scrolling list of allowed users

### ISSUE THREAD

**Issue by oijkn** [thurban/plugin_weathermap#18]
Hi @thurban,

When i tried to add an user to a map I can't scroll in the list. I will try to fix it, maybe you are aware of this bug?

Actually I have more than 1k users.

**Comment by channdy** [comment]
I got this issue as well on Cacti 1.2.22 so there is a fix for it.

**Comment by DatBoiTroy** [comment]
I've seen this issue for a while. Are you using the Modern theme on Cacti? If so, trying switching to the Classic theme and try again. I typically have to do this when making changes to the user list for Weathermaps.

**Comment by channdy** [comment]
> I've seen this issue for a while. Are you using the Modern theme on Cacti? If so, trying switching to the Classic theme and try again. I typically have to do this when making changes to the user list for Weathermaps.

Yes, no issue with the Classic theme. Thanks

**Comment by TheWitness** [comment]
@channdy, @oijkn  and @DatBoiTroy, There is a large pull request coming in, but though I knew that this was going to be an issue, I did not address it in the pull request.  So, I'll keep it opened.  Keep your eyes peeled for this one going in.  After which we will start a beta.

https://github.com/Cacti/plugin_weathermap/pull/39

**Comment by TheWitness** [comment]
Related to this: 

https://github.com/Cacti/plugin_weathermap/issues/43
