### ISSUE TITLE
Cacti ver 1.2.16 - editor can't edit at all

### ISSUE THREAD

**Issue by mulera84** [thurban/plugin_weathermap#19]
when opening a map for editing I can see all old conf but can't change anything

editor.js:44 Uncaught TypeError: jQuery(...).unload is not a function
    at editor.js:44

jquery.min.js:2 Uncaught Error: Syntax error, unrecognized expression: area[id^=LINK:]
    at Function.oe.error (jquery.min.js:2)
    at oe.tokenize (jquery.min.js:2)
    at oe.select (jquery.min.js:2)
    at Function.oe [as find] (jquery.min.js:2)
    at w.fn.init.find (jquery.min.js:2)
    at new w.fn.init (jquery.min.js:2)
    at w (jquery.min.js:2)
    at attach_click_events (editor.js:88)
    at HTMLDocument.initJS (editor.js:66)
    at l (jquery.min.js:2)

**Comment by gurudvlp** [comment]
I ran into this same issue the day after you posted this.  I'm no longer seeing the same error messages (no idea why), but I got this working by setting permissions on the weathermap/configs directory to 770.  Something like:

chown root:www-data configs -R
chmod ug+rwx configs -R
chmod o-rwx configs -R

Hopefully this helps.

**Comment by gand0lfi** [comment]
Yes, this is right, it´s only because there are no write permissions on the on the weathermap/configs directory. this issue should be closed.

**Comment by TheWitness** [comment]
This issue will be resolved once this pull request is merged: https://github.com/Cacti/plugin_weathermap/pull/39

Though I will add, you still must, as the web browser, have rights to the Weathermap configs directory.
