### ISSUE TITLE
No Image "button_go.gif" in Cacti 1.2.8

### ISSUE THREAD

**Issue by leonardo0014** [thurban/plugin_weathermap#2]
Hello

The image for "button_go.gif" is no longer available in Cacti version 1.2.8. You better use "enable_icon.png" for that.

https://github.com/thurban/plugin_weathermap/blob/29a87099581e50ba386c7490d583f332ea4c26e6/weathermap-cacti-plugin.php#L802

MfG
Leo

**Comment by thurban** [comment]
changed with latest commit
