### ISSUE TITLE
Hover Does not work properly

### ISSUE THREAD

**Issue by zuka1337** [thurban/plugin_weathermap#23]
Hover:

![image](https://user-images.githubusercontent.com/57998098/114438859-37f8a400-9bc0-11eb-8c42-c92ffa94b8a8.png)

**Comment by zuka1337** [comment]
Content-Security Allow Unsafe JavaScript eval() calls = yes

**Comment by TheWitness** [comment]
This issue will be resolved once this pull request is merged: https://github.com/Cacti/plugin_weathermap/pull/39

**Comment by TheWitness** [comment]
@zuka1337, once the pull request is merged, overlib will be gone.  Replaced by jQueryUI tooltips.
