### ISSUE TITLE
Logged error message when setting 'none' as scale color

### ISSUE THREAD

**Issue by lclbo** [thurban/plugin_weathermap#24]
When using a scale for displaying custom link states, a PHP error is recorded on each execution if a color is set to 'none':

(please note that some line numbers might be off by 4-8 lines since I already had my fix in place but commented it to recreate the error code)
> CMDPHP PHP ERROR WARNING 
> Backtrace: (/poller.php[754]:api_plugin_hook(), /lib/plugins.php[74]:api_plugin_run_plugin_hook(), /lib/plugins.php[177]:weathermap_poller_bottom(), /plugins/weathermap/setup.php[787]:weathermap_run_maps(), /plugins/weathermap/lib/poller-common.php[211]:WeatherMap->DrawMap(), /plugins/weathermap/lib/Weathermap.class.php[3255]:WeatherMap->AllocateScaleColours(), /plugins/weathermap/lib/Weathermap.class.php[3163]:myimagecolorallocate(), /plugins/weathermap/lib/WeatherMap.functions.php[283]:imagecolorallocate(), CactiErrorHandler())  

and  

>ERROR PHP WARNING in Plugin 'weathermap': imagecolorallocate(): Red component is out of range in file: /usr/share/cacti/site/plugins/weathermap/lib/WeatherMap.functions.php on line: 283 

My scale definition is:
```
SCALE updown 0 0 none 0.png
SCALE updown 2 2 none 2.png
SCALE updown 1 1 none 1.png
```

As far as I could track down the error, it seems that the massive Regex in Weathermap.class.php (around line 3163) sets $red, $green and $blue to -1 if 'none' is set instead of a color.
This leads to a PHP error when executing either imagecolorallocate() or imagecolorexact() in function myimagecolorallocate() in WeatherMap.functions.php in the lines after 267.

My fix was to allocate a transparent color if -1 is set for either of R,G,B, so my fixed myimagecolorallocate() is:

```
// wrapper around imagecolorallocate to try and re-use palette slots where possible
function myimagecolorallocate($image, $red, $green, $blue)
{
        // it's possible that we're being called early - just return straight away, in that case
        if(!isset($image)) return(-1);

        // fix "component out of range" issue for 'none' colors, where R,G,B are set to -1
        // creates a 'none' color by allocating black with full transparency
        // maybe this issue can even better be avoided at Weathermap.class.php[3163] ??
        if($red<0 || $green<0 || $blue<0)
                return (imagecolorallocatealpha($image, 0, 0, 0, 127));

        $existing=imagecolorexact($image, $red, $green, $blue);

        if ($existing > -1)
                return $existing;

        return (imagecolorallocate($image, $red, $green, $blue));
}
```

I think it might be better to catch a 'none'-color already at the regex, but I did not want to break anything else, so this was the less invasive fix for me.

**Comment by TheWitness** [comment]
@lclbo, you should re-evaluate this bug once the following pull request is merged: https://github.com/Cacti/plugin_weathermap/pull/39

**Comment by TheWitness** [comment]
@lclbo , if you could do the pull request, that would be awesome.  Let me know you can do it.

**Comment by TheWitness** [comment]
Okay, this is fixed now
