### ISSUE TITLE
ERROR PHP WARNING

### ISSUE THREAD

**Issue by fredouil66** [thurban/plugin_weathermap#25]
Hi,
I can't manage to fix this error.
I'm on V1.2.14
All seems to work well, just this error I cant get my head arround...

![image](https://user-images.githubusercontent.com/71542898/124446393-aba1eb80-dd80-11eb-91a9-49c6411e235d.png)

<html><body>

05/07/2021  11:05:12 - ERROR PHP WARNING in  Plugin 'weathermap': A non-numeric  value encountered in file:  /opt/cacti/plugins/weathermap/lib/Weathermap.class.php  on line: 975
--
05/07/2021 11:05:12 - CMDPHP PHP ERROR WARNING Backtrace:   (/poller.php[823]:api_plugin_hook(),  /lib/plugins.php[74]:api_plugin_run_plugin_hook(),  /lib/plugins.php[177]:weathermap_poller_bottom(),  /plugins/weathermap/setup.php[787]:weathermap_run_maps(),  /plugins/weathermap/lib/poller-common.php[195]:WeatherMap->ReadData(),  /plugins/weathermap/lib/Weathermap.class.php[974]:CactiErrorHandler())
05/07/2021 11:05:12 - ERROR PHP WARNING in  Plugin 'weathermap': A  non-numeric value encountered in file:  /opt/cacti/plugins/weathermap/lib/Weathermap.class.php  on line: 974
05/07/2021 11:05:12 - CMDPHP PHP ERROR WARNING Backtrace:   (/poller.php[823]:api_plugin_hook(),  /lib/plugins.php[74]:api_plugin_run_plugin_hook(),  /lib/plugins.php[177]:weathermap_poller_bottom(),  /plugins/weathermap/setup.php[787]:weathermap_run_maps(),  /plugins/weathermap/lib/poller-common.php[195]:WeatherMap->ReadData(),  /plugins/weathermap/lib/Weathermap.class.php[975]:CactiErrorHandler())
05/07/2021 11:05:12 - ERROR PHP WARNING in  Plugin 'weathermap': A  non-numeric value encountered in file:  /opt/cacti/plugins/weathermap/lib/Weathermap.class.php  on line: 975
05/07/2021 11:05:12 - CMDPHP PHP ERROR WARNING Backtrace:   (/poller.php[823]:api_plugin_hook(),  /lib/plugins.php[74]:api_plugin_run_plugin_hook(),  /lib/plugins.php[177]:weathermap_poller_bottom(),  /plugins/weathermap/setup.php[787]:weathermap_run_maps(),  /plugins/weathermap/lib/poller-common.php[195]:WeatherMap->ReadData(),  /plugins/weathermap/lib/Weathermap.class.php[974]:CactiErrorHandler())
05/07/2021 11:05:12 - ERROR PHP WARNING in  Plugin 'weathermap': A  non-numeric value encountered in file:  /opt/cacti/plugins/weathermap/lib/Weathermap.class.php  on line: 974

</body>
</html>

**Comment by howardjones** [comment]
What do your TARGETs look like for this map? (Specifically any that have a multiplication in them)

**Comment by fredouil66** [comment]
I got read of all multiplications and only put values in bits since a few months because i had problems with PHP.
here is what I did:
![Capture](https://user-images.githubusercontent.com/71542898/124471755-8bccf080-dd9d-11eb-9ccb-d81c7b906a10.PNG)
![weathermap-cacti-plugin](https://user-images.githubusercontent.com/71542898/124471760-8d96b400-dd9d-11eb-94ad-47d2c01b1c82.png)
![weathermap-cacti-plugin1](https://user-images.githubusercontent.com/71542898/124471765-8f607780-dd9d-11eb-9edf-9db67565793d.png)
[Serveur_F.cont.txt](https://github.com/thurban/plugin_weathermap/files/6764175/Serveur_F.cont.txt)

**Comment by fredouil66** [comment]
![weathermap-cacti-plugin](https://user-images.githubusercontent.com/71542898/124471909-c3d43380-dd9d-11eb-9450-3c221d55f012.png)

**Comment by fredouil66** [comment]
![Capture1](https://user-images.githubusercontent.com/71542898/124472222-25949d80-dd9e-11eb-9329-890dbb29ab78.PNG)
![Capture2](https://user-images.githubusercontent.com/71542898/124472264-334a2300-dd9e-11eb-8991-1cbff29d0416.PNG)

**Comment by howardjones** [comment]
So the part that is failing is only run if it thinks multiply is necessary.

```
		if($multiply != 1) {  
			wm_debug("Pre-multiply: $in $out\n"); 
								
			$in = $multiply*$in;  # <-- this is line 974
			$out = $multiply*$out;
								
			wm_debug("Post-multiply: $in $out\n"); 
		}
```
								
If you run with DEBUG logging, what do the logs say before the error?

**Comment by TheWitness** [comment]
This should be addressed.  Keeping this open for the moment though.

You should re-evaluate in a non production settings once this pull request is merged: https://github.com/Cacti/plugin_weathermap/pull/39

**Comment by fredouil66** [comment]
ok I'm on the 1.2.22 version of cacti is it good to be able to test the plugin? when I have tested it I will return to you with pleasure

**Comment by TheWitness** [comment]
Yea, it should work find on 1.2.22.  @bmfmancini, who I have asked to coordinate a beta release and I are doing some system and unit testing on the plugin right now.  It's in my personal repo for the moment.  If you want to dig in, grab it.  But be careful is it's production.  Have a good testing location to work with it in.

**Comment by TheWitness** [comment]
Going to close this one.  Goto the Beta Test and use it on Cacti 1.2.23 and provide feedback.  It's a pretty heavy rewrite.
