### ISSUE TITLE
 i can't create map

### ISSUE THREAD

**Issue by BrunerHoes** [thurban/plugin_weathermap#26]
hi, i am a new user of cacti and weathermap. 
i have install cacti 1.2.15 and weathermap. 
i have install cacti without bug but when i try to create i new map nothing happend

**Comment by BrunerHoes** [comment]
is ok now i just have to add ".conf" after the name of my map

**Comment by TheWitness** [comment]
This issue will be resolved once this pull request is merged: https://github.com/Cacti/plugin_weathermap/pull/39
