### ISSUE TITLE
error cacti weathermap 

### ISSUE THREAD

**Issue by youyou14** [thurban/plugin_weathermap#27]
hi, 

i am a new user of cacti and weather map
i have this error , i don't know why : 
![image](https://user-images.githubusercontent.com/18118455/130221353-8025a7f7-b791-40a1-9770-53d5c9f1c07a.png)
 and also this for graph : 
![image](https://user-images.githubusercontent.com/18118455/130221463-5cbaa135-420b-460f-8f26-387f14d2c5ef.png)

can you help me please

**Comment by TheWitness** [comment]
This issue will be resolved once this pull request is merged: https://github.com/Cacti/plugin_weathermap/pull/39

The cacti-picker.php was removed from this large update.  You will want to pay close attention to the files that were removed from this pending release.
