### ISSUE TITLE
error install weathermap cacti 2.1.18

### ISSUE THREAD

**Issue by youyou14** [thurban/plugin_weathermap#28]
hi, 

i had try to install cacti 3 times, but every time, the weathermap don't working 
i have the : 
cacti 1.2.18
spine 1.2.18

PHP 7.4.3
MariaDB 10.3.31
OS : ubuntu server 20.04

![image](https://user-images.githubusercontent.com/18118455/130372624-e29e6a9f-174c-4632-b53b-6523d80f7f4a.png)
 thanks

**Comment by TheWitness** [comment]
This issue will be resolved once this pull request is merged: https://github.com/Cacti/plugin_weathermap/pull/39
