### ISSUE TITLE
Weathermap setup.php fails to create sql tables on cacti 1.2.10

### ISSUE THREAD

**Issue by zornorph** [thurban/plugin_weathermap#33]
OS: Ubuntu 20.04
DB: mysql 8.0.28
Cacti: 1.2.10
Spine: 1.2.6

Extracted weathermap zip onto server into plugins directory, ran check.php from browser and cli, both came back ok with no errors. However when clicking "install plugin" I get these errors:

2022/04/01 18:27:41 - CMDPHP SQL Backtrace: (/plugins.php[25]:include(), /include/auth.php[28]:require_once(), /include/global.php[484]:include_once(), /include/global_arrays.php[2718]:api_plugin_hook(), /lib/plugins.php[74]:api_plugin_run_plugin_hook(), /lib/plugins.php[177]:weathermap_config_arrays(), /usr/local/share/cacti/plugins/weathermap/setup.php[478]:api_plugin_register_realm(), /lib/plugins.php[882]:db_execute_prepared())
2022/04/01 18:27:41 - CMDPHP ERROR: A DB Exec Failed!, Error: Column 'user_id' cannot be null
2022/04/01 18:27:41 - CMDPHP SQL Backtrace: (/plugins.php[25]:include(), /include/auth.php[28]:require_once(), /include/global.php[484]:include_once(), /include/global_arrays.php[2718]:api_plugin_hook(), /lib/plugins.php[74]:api_plugin_run_plugin_hook(), /lib/plugins.php[177]:weathermap_config_arrays(), /usr/local/share/cacti/plugins/weathermap/setup.php[477]:api_plugin_register_realm(), /lib/plugins.php[882]:db_execute_prepared())
2022/04/01 18:27:41 - CMDPHP ERROR: A DB Exec Failed!, Error: Column 'user_id' cannot be null
2022/04/01 18:27:41 - CMDPHP SQL Backtrace: (/plugins.php[25]:include(), /include/auth.php[28]:require_once(), /include/global.php[484]:include_once(), /include/global_arrays.php[2718]:api_plugin_hook(), /lib/plugins.php[74]:api_plugin_run_plugin_hook(), /lib/plugins.php[177]:weathermap_config_arrays(), /usr/local/share/cacti/plugins/weathermap/setup.php[476]:api_plugin_register_realm(), /lib/plugins.php[882]:db_execute_prepared())
2022/04/01 18:27:41 - CMDPHP ERROR: A DB Exec Failed!, Error: Column 'user_id' cannot be null 

Trying to continue by clicking "enable plugin" just gives a lot of errors similar to the following:

2022/04/01 18:50:02 - CMDPHP ERROR: A DB Row Failed!, Error: Table 'cacti.weathermap_data' doesn't exist

**Comment by TheWitness** [comment]
This issue will be resolved once this pull request is merged: https://github.com/Cacti/plugin_weathermap/pull/39
