### ISSUE TITLE
Null error

### ISSUE THREAD

**Issue by dream-hunter** [thurban/plugin_weathermap#38]
There is a bug with null value that happens quite often on host edit. After that cacti disables weathermap plugin.
https://github.com/Cacti/plugin_weathermap/blob/a6eac2deb791fcf39735d68b4560b3cae24328db/cacti-pick.php#L114

I advice to change it similar to this:
```
if ($hostid > 0 && !is_null($_SESSION['cacti']['weathermap']['last_used_host_id']) && !in_array($hostid, $_SESSION['cacti']['weathermap']['last_used_host_id'])) {
```

**Comment by TheWitness** [comment]
This issue will be resolved once this pull request is merged: https://github.com/Cacti/plugin_weathermap/pull/39
