### ISSUE TITLE
1.0 - QA Add support for other data source types and graphs

### ISSUE THREAD

**Issue by thurban** [thurban/plugin_weathermap#45]
Currently, the editor.inc.php file limits the datasource and graphs selection to the following template

` 43 | 5deb0d66c81262843dce5f3861be9966 | Interface - Traffic (bits/sec) `

using this SQL statement:

`$sql_where .= ($sql_where != '' ? ' AND ':'WHERE ') . 'gt.hash = "5deb0d66c81262843dce5f3861be9966"';`

It should support other interface traffic types ( generic graph types?) as well

**Comment by TheWitness** [comment]
This is resolved here: https://github.com/TheWitness/plugin_weathermap/commit/aaf9ce9b92194f75a9d4f18b11d4ce34bf944f0f
