### ISSUE TITLE
1.0 - QA When adding datasources or graphs using the Add button, a space will always be added

### ISSUE THREAD

**Issue by thurban** [thurban/plugin_weathermap#46]
When pressing the Add buttong for "Graph Selector" on the Nodes Screen or "Graphs Selector" and "Data Soiurce Selector" on Link screen a space will be added to the front of the "Data Source(s)" and "Hover Graph URL(s)" even when the field is empty.

The expected behaviour is that for the first/initial item ( field is still empty ), there will be no additional space added.

![grafik](https://user-images.githubusercontent.com/17292964/210273550-b5c2fa0f-d928-4e9e-91a1-7d03b0c5fc3f.png)
![grafik](https://user-images.githubusercontent.com/17292964/210273558-5abd8bf1-19c8-4119-aa25-06cb2a971c8d.png)

**Comment by TheWitness** [comment]
This has been resolved here: https://github.com/TheWitness/plugin_weathermap/commit/aaf9ce9b92194f75a9d4f18b11d4ce34bf944f0f
