### ISSUE TITLE
Link creation it's opposit

### ISSUE THREAD

**Issue by GrayFox14048** [thurban/plugin_weathermap#50]
link creation it's opposit, I mean when you create a link between two nodes, the first you select will be not the start but the end

**Comment by TheWitness** [comment]
Can you please show a visual?

**Comment by TheWitness** [comment]
@GrayFox14048, can you please respond to my inquiry?

**Comment by GrayFox14048** [comment]
> @GrayFox14048, can you please respond to my inquiry?

It's not easy to take a screenshot about that. I try to explain: In the old version of weathermap, between 2 nodes, when you create a link, the first one you click on it was the "source", now the first node you click on is the destination but the label is the same of the source, isn't like that for you?

**Comment by GrayFox14048** [comment]
it's not a big problem, but maybe you can edit the label, and let know the difference with the old version

**Comment by TheWitness** [comment]
@jdcoats, can you explain this one to me?

**Comment by jdcoats** [comment]
Not really I've always been confused by that though, I just swap the nodes if I feel they are backwards in the dataflow. In the end network traffic is bidirectional :) Imagine this create a link between router and cloud, knowing that the majority of the traffic is download. You would'nt want the arrow to be pointing outbound in the traffic.

![image](https://user-images.githubusercontent.com/42470924/213567060-91457a19-79f0-4d7f-802b-9206e8284fd3.png)

This all depends on which device perspective you select the graph from also. It could be said its not backwards you just selected the graph for the opposite end of the connection.

**Comment by TheWitness** [comment]
I'll go ahead and reverse it for now.  See how that goes.

**Comment by TheWitness** [comment]
Okay, should be resolved in my copy of the repo.

**Comment by TheWitness** [comment]
@GrayFox14048, check it out.
