### ISSUE TITLE
editor chooser not working

### ISSUE THREAD

**Issue by jdcoats** [thurban/plugin_weathermap#58]
looking for BIXLER-CORE-7009-01-N7K2-port-channel5-L3 Mustian-9300-01
![image](https://user-images.githubusercontent.com/42470924/213346340-ba054858-e4e0-4f80-815f-7c8637225dee.png)
will not show up any way I try it. Search for BIXLER-CORE-7009-01-N7K2-port-channel5 returns results shown in screenshot but no way to pick the graph I want
![image](https://user-images.githubusercontent.com/42470924/213346798-f180c155-041a-4f0e-849e-cce846e390bd.png)

**Comment by jdcoats** [comment]
yeah the datasource selector does not work at all, even selecting a datasource that the selector does find enters a invalid rrd path like /8679/1234.rrd instead of /path/to/cacti/rra/8679/1234.rrd or it will just enter the graph title instead of an path to rrd at all.

**Comment by TheWitness** [comment]
@jdcoats, it's supposed to use the 'relative' path (to save space) and then find the realpath during collection.  I'm wondering how the leading slash ended up in the front of the path?  You should be able to use the full path, but the relative path, if it's Cacti should also be okay.

**Comment by jdcoats** [comment]
okay update, maybe I should have tested more thoroughly. If you copy+paste the datasource name precisely with no leading or trailing space it will find the datasource. If there is a leading or trailing space in copy+paste it will not find your search. additionally if you search for something like port-channel5 or po5 It would be a nice feature to find all datasources containing that. I concede last night when testing that after upgrading I let it re-install all packages and it changed my suggested names order and I didn't catch that the graph name and datasource name didn't always match :)  I fixed my own problem there and the datasource selector isn't completely broken and could simply use a little TLC, the search list when typing could be longer maybe 100 because port-channel5 above in my screenshot had to many results to display what i wanted to choose? 
The relative path does indeed work fine. To much wine on initial testing.

**Comment by TheWitness** [comment]
> okay update, maybe I should have tested more thoroughly. If you copy+paste the datasource name precisely with no leading or trailing space it will find the datasource. If there is a leading or trailing space in copy+paste it will not find your search

Got it.

> additionally if you search for something like port-channel5 or po5 It would be a nice feature to find all datasources containing that

I'll validate this.

>  I fixed my own problem there and the datasource selector isn't completely broken and could simply use a little TLC

Cool.

>  the search list when typing could be longer maybe 100 because port-channel5 above in my screenshot had to many results to display what i wanted to choose?

This is configurable: Console > Setting > Visual > Autocomplete Rows

> The relative path does indeed work fine. To much wine on initial testing.

I'll drink to that.

**Comment by jdcoats** [comment]
wow, i like learning new stuff, Is autocomplete rows setting new?  :) Thanks!

**Comment by TheWitness** [comment]
So, does you discovering that "tweak" for Autocomplete address my second comment above?

**Comment by TheWitness** [comment]
@netniV want's infinite scroll, and that's possible with jQueryUI, but we are going to defer that to 1.3.x.  I'll take a brief look for this plugin as I think it's doing it's own thing and not using the Cacti API (at least I don't think so).

**Comment by TheWitness** [comment]
Confirming that I hacked (just for WeatherMap) what is currently a part of Cacti mainline (develop) for autocomplete.

**Comment by jdcoats** [comment]
yes the datasource selector and graph selector work fine when expanding autocomplete! :)

**Comment by TheWitness** [comment]
Cool.
