### ISSUE TITLE
Missing ICON data

### ISSUE THREAD

**Issue by arno-st** [thurban/plugin_weathermap#62]
the ICON of style 'none' and 'nink' are not available
They where none for label without ICON, and nink it's a ying/yang style with percent displayed inside for in and out.
`
24/01/2023 14:37:34 - WEATHERMAP WARNING: ICONFILE file not found on disk: /usr/share/cacti/plugins/weathermap/50 50 nink skipping! [WMPOLL12]
24/01/2023 14:37:34 - WEATHERMAP WARNING: ICONFILE file not found on disk: /usr/share/cacti/plugins/weathermap/50 50 none skipping! [WMPOLL12]
`
It's a file but something build inside weathermap (can't find the source of it yet, I will dig into it)

**Comment by TheWitness** [comment]
Please run the cli script `upgrade_configs.php` as an account that is able to write to the images directory.

**Comment by TheWitness** [comment]
Better take either beta3, or what's in my personal repo.  I made a big assumption that was wrong.  Fixed now.

**Comment by arno-st** [comment]
Well in Beta2 Iwas able to edit a map an select ICON none so just label, but after 3 change I got this error:

`
30/01/2023  13:30:43 - CMDPHP PHP ERROR NOTICE Backtrace:   (/plugins/weathermap/weathermap-cacti-plugin-editor.php[173]:setNodeProperties(),   /plugins/weathermap/lib/editor.actions.php[314]:WeatherMap->WriteConfig(),  /plugins/weathermap/lib/WeatherMap.class.php[3380]:CactiErrorHandler())
--
30/01/2023 13:30:43 - ERROR PHP NOTICE in  Plugin 'weathermap':  Undefined property: stdClass::$name in file:  /usr/share/cacti/plugins/weathermap/lib/WeatherMap.class.php  on line:  3380
30/01/2023 13:30:43 - CMDPHP PHP ERROR WARNING Backtrace:   (/plugins/weathermap/weathermap-cacti-plugin-editor.php[173]:setNodeProperties(),  /plugins/weathermap/lib/editor.actions.php[294]:CactiErrorHandler())
30/01/2023 13:30:43 - ERROR PHP WARNING in  Plugin 'weathermap':  Creating default object from empty value in file:  /usr/share/cacti/plugins/weathermap/lib/editor.actions.php  on line: 294
`

Maybe an issue with the letter used:
`
NODE DC_Praz-SÃ©chaud
        LABEL DC_Praz-SÃ©chaud
        POSITION 1740 75
`

That 'Ã©' displayed as é

**Comment by TheWitness** [comment]
Go to line 169 in lib/editor.inc.php and change `urlencode` to `html_escape`, and then try the action again.

**Comment by TheWitness** [comment]
Oh, and this is a separate issue.

**Comment by TheWitness** [comment]
Please open a new case.
