### ISSUE TITLE
LOG:ICONFILE file not found.When using the specified icon.

### ISSUE THREAD

**Issue by jackfish0405** [thurban/plugin_weathermap#63]
Specifies the icon to use for the node. The log reports an error.

CONFIG:
NODE node04795
	LABEL HMY-GXNN
	LABELFONT 5
	LABELOUTLINECOLOR none
	LABELBGCOLOR 255 204 0
	LABELFONTCOLOR contrast
	ICON 180 40 rbox
	POSITION 100 100

LOG:
2023-01-25 15:48:11 - WEATHERMAP WARNING: ICONFILE file not found on disk: /var/www/html/cacti/plugins/weathermap/80 50 round skipping! [WMPOLL12]
2023-01-25 15:48:11 - WEATHERMAP WARNING: ICONFILE file not found on disk: /var/www/html/cacti/plugins/weathermap/220 40 rbox skipping! [WMPOLL12]
2023-01-25 15:48:11 - WEATHERMAP WARNING: ICONFILE file not found on disk: /var/www/html/cacti/plugins/weathermap/180 40 rbox skipping! [WMPOLL12]

**Comment by TheWitness** [comment]
Appreciate you logging this can you show from your production instance how this attribute was previously rendered.  I'll be reviewing this week's bugs over the weekend.

**Comment by jackfish0405** [comment]
Data is copied from the production environment。
Production instance display：
![image](https://user-images.githubusercontent.com/53333879/214560658-44504654-ee8b-48a1-8ed4-2fb5dad55a97.png)
config:
![image](https://user-images.githubusercontent.com/53333879/214561180-dc860ee5-afbd-4159-990d-176d8600f05f.png)
![image](https://user-images.githubusercontent.com/53333879/214561263-f01ea632-93dd-4664-ac9c-c04939f7891f.png)
beta2 config:
![image](https://user-images.githubusercontent.com/53333879/214561476-f983a900-0c3a-441a-bc28-3a9cfdc97ac3.png)
![image](https://user-images.githubusercontent.com/53333879/214561803-9afb97f9-bffc-4510-9a32-04fb6feb4f9d.png)

**Comment by TheWitness** [comment]
I was wondering, what in the heck is "Artificial Icon".  I took it out which would explain it.  So, if you could elaborate?  Got to give it a new name...

**Comment by jackfish0405** [comment]
I'm not very good at explaining either. Can refer to the original document?
https://www.network-weathermap.com/manual/0.98/pages/config-reference.html#LINK_COLORS
![image](https://user-images.githubusercontent.com/53333879/214567349-e2bd0b29-13ee-4268-b9b1-c2089896fb7a.png)

**Comment by TheWitness** [comment]
Okay, so as I read it, Howie basically would leave the config file alone if there was an Artificial Icon.  So, that sounds like it was maybe a little hackish, am I reading that right?

**Comment by TheWitness** [comment]
Well, it was hackish, but not fixing it today.  Feature list for future reference.  You will have to restore your config files from the production system.

**Comment by TheWitness** [comment]
You can find this in my personal repo until the next beta, or release.
