### ISSUE TITLE
The problem with the default width of the hover map

### ISSUE THREAD

**Issue by jackfish0405** [thurban/plugin_weathermap#65]
Increase the default width of the hover map, which is not fully displayed, and the rightmost part of the map is not displayed.

config：
![image](https://user-images.githubusercontent.com/53333879/214519948-501364f9-5b3f-48a3-b0b0-e236d3bfbb76.png)

hover map：
![image](https://user-images.githubusercontent.com/53333879/214517801-85fc1f7a-7c90-4548-a2ff-37a7af225da2.png)

original map:
![image](https://user-images.githubusercontent.com/53333879/214520452-4d711cc5-15f2-4982-a5bf-a2150a1690b2.png)

**Comment by TheWitness** [comment]
What is the graph image size currently?  Not material, just curious.

**Comment by jackfish0405** [comment]
I like to keep the image size consistent with cacti, for example  width="795pt" height="342pt".
In previous versions, OVERLIBWIDTH and OVERLIBHEIGHT were used in LINK TEMPLATE.
![image](https://user-images.githubusercontent.com/53333879/214575189-a921cb4c-7d4e-4008-bd8d-2c83a31be84e.png)

**Comment by TheWitness** [comment]
Hmm, so, was overlib resizing the images dynamically?  Though overlib is gone, resizing does not have to be a problem, just need confirmation.

**Comment by jackfish0405** [comment]
I think the maximum width of the white border is limited to 500 pixels, and the border cannot follow the image to expand after the image width exceeds 500 pixels.

500*200 config The image is displayed in its entirety.
![image](https://user-images.githubusercontent.com/53333879/214767023-cd3d3c4b-420b-43d4-a400-40d6f46f0379.png)
![image](https://user-images.githubusercontent.com/53333879/214766755-c0faaac7-4362-4159-a632-6f866d3d2024.png)

550*200 config The right side of the image is partially covered by a white frame and is not fully displayed.
![image](https://user-images.githubusercontent.com/53333879/214766982-d9d15ffd-6b58-468e-bbf0-47dddbfd6798.png)
![image](https://user-images.githubusercontent.com/53333879/214766886-05dafeaf-955f-4518-9b58-f1d557bf2812.png)

In the previous version, it seems that OVERLIB zooms the image as a whole, but the current version only adjusts the length and width of the coordinate map, and the IN/OUT values ​​below do not follow the zoom adjustment.
![image](https://user-images.githubusercontent.com/53333879/214767559-be285f12-d15c-4957-852d-649de070fa91.png)
![image](https://user-images.githubusercontent.com/53333879/214768516-0573553a-9d05-470d-8e71-aec775b321a2.png)

**Comment by jackfish0405** [comment]
I think removing the width limit of 500px from the white border should allow the full display?

**Comment by TheWitness** [comment]
It'll all be managed by JavaScript, just have to get to it.

**Comment by jackfish0405** [comment]
Ok, I don't understand code. Which line of code in which JavaScript file controls the border width limit? Should I just change it locally to the value I need? thanks

**Comment by jackfish0405** [comment]
It should be a problem with my configuration. Carrying "OVERLIBWIDTH 795 OVERLIBHEIGHT 346" when copied from a previous version of the configuration. After removing it it looks normal. By the way, is it normal that there is always a blank space on the left?
![image](https://user-images.githubusercontent.com/53333879/215089388-104414e6-e4e1-4d06-a78e-a2737627121a.png)

**Comment by TheWitness** [comment]
You got time for a quick zoom?

**Comment by TheWitness** [comment]
@jackfish0405 can you do a zoom?

**Comment by jackfish0405** [comment]
Sorry, I have never used zoom. My English is very bad, so I rely on Google Translate. I think video communication will be difficult. Ha ha. I found that tooltip.css is in the weathermap.js file, and I can modify my local file as needed. Thank you for your help.

**Comment by TheWitness** [comment]
This is resolved no and will be a part of beta3.
