### ISSUE TITLE
 Automatic refresh of webpage will not work 

### ISSUE THREAD

**Issue by jackfish0405** [thurban/plugin_weathermap#66]
Automatic refresh of webpage will not work 。Only manually to refresh the page.
config:
![image](https://user-images.githubusercontent.com/53333879/214524429-02602f47-99a2-4628-b534-45e6c4ed2d77.png)

**Comment by TheWitness** [comment]
Your talking about the main Weathermap page right?

**Comment by jackfish0405** [comment]
Yes, the weather-map on this page does not automatically refresh every minute
![image](https://user-images.githubusercontent.com/53333879/214577518-8e9b0aef-f618-4806-b4dd-b690a35114c3.png)

**Comment by TheWitness** [comment]
Okay, there is a nice API for that.

**Comment by TheWitness** [comment]
Okay, this is resolved in my personal repo till beta3 or release.
