### ISSUE TITLE
CSS improvements

### ISSUE THREAD

**Issue by dream-hunter** [thurban/plugin_weathermap#70]
There are problem with viewing the big maps. It would be good to add into weathermap.css something like this:
```
.cacti Graph Content Area {
        overflow-x: auto !important;
}
```

With editor everything looks more complicated. I don't even know a short way to fix the issue with big maps here. (((

**Comment by TheWitness** [comment]
Yea, that's already fixed in my personal repo.

**Comment by TheWitness** [comment]
You think it's complicated now, the whole thing was totally complicated before.  That's just my opinion.

**Comment by TheWitness** [comment]
https://github.com/TheWitness/plugin_weathermap
