### ISSUE TITLE
 The OVERLIBGRAPH of the link at the edge position is outside the bounding box.

### ISSUE THREAD

**Issue by jackfish0405** [thurban/plugin_weathermap#71]
The OVERLIBGRAPH of the link at the edge position is outside the bounding box.The graph display is incomplete.

![image](https://user-images.githubusercontent.com/53333879/215238224-02a086da-8493-4398-8348-dd92d8f357ea.png)
![image](https://user-images.githubusercontent.com/53333879/215238264-6eda4ef8-03a1-42bc-a611-02bb9c9d98ee.png)

The previous version will automatically hover in the appropriate position after using 'OVERLIBWIDTH OVERLIBHEIGHT'.

![image](https://user-images.githubusercontent.com/53333879/215238496-533b2275-c540-4f73-bf65-7abf80632d90.png)
![image](https://user-images.githubusercontent.com/53333879/215238582-6288c90b-b50c-45e3-9233-abb01eef629f.png)

**Comment by TheWitness** [comment]
Those variables have no use in my current version in my personal repo.

**Comment by TheWitness** [comment]
Remember, overlib is gone.  All that remains are variable names.

**Comment by jackfish0405** [comment]
Ok, is there a new way to make the graph automatically adjust to the appropriate position? When the link is close to the border, it is always displayed incompletely because it exceeds the border.

**Comment by TheWitness** [comment]
I'll probably write it tomorrow.

**Comment by jackfish0405** [comment]
Thanks for your work.

**Comment by TheWitness** [comment]
Closing as duplicate
