### ISSUE TITLE
 weathermap editor page issue

### ISSUE THREAD

**Issue by jackfish0405** [thurban/plugin_weathermap#74]
**The weathermap editor page does not have a right vertical scroll bar and a bottom horizontal scroll bar.** 

![image](https://user-images.githubusercontent.com/53333879/215384421-1726181b-4e50-4958-a327-468253ad1f39.png)

**Failed to create a new node, in the red box area outside the screen display area of ​​high pixel MAP.**
**Nodes are automatically added to other locations, as marked by red ellipses.**
![image](https://user-images.githubusercontent.com/53333879/215388223-335ae943-76a9-40ef-b579-37ee74acd019.png)

**Comment by TheWitness** [comment]
It's a permission problem, not a plugin problem.

**Comment by jackfish0405** [comment]
At first it was a permission problem, but I later found out that I forgot to modify the config permission.Now update the description of the problem. I don’t think the current problem is a permission problem. You can test it. Create a 4000*4000 graph and fail to add nodes near the right border and bottom area. Nodes are automatically added to the middle area. And，The weathermap editor page does not have a right vertical scroll bar and a bottom horizontal scroll bar.In this way, nodes and links outside the displayed area cannot be edited.

**Comment by TheWitness** [comment]
Got it.

**Comment by TheWitness** [comment]
What's odd is that in the case of adding a node, when I scroll, I can create a new object just fine in the red areas.  It seems on the vertical side, where I have the scroll bar, as should you, I can create an object, but on the horizontal side, where I don't have a scroll bar, I can not, even though the cursor is properly showing the x and y axes.  Weird.

![Odd Scroll Behavior](https://user-images.githubusercontent.com/1439914/215491065-f94c0f04-be91-4ee2-986a-4427dfc699ce.gif)

**Comment by jackfish0405** [comment]
In my case neither vertical nor horizontal scrollbar. The MAP is set to 4000*2000, but when the cursor moves to the boundary, the X-axis position coordinates actually display 1535. The Y-axis position coordinates actually display 740. It seems to be related to my display resolution. Not the setting value of MAP. My browser is chrome.
![1](https://user-images.githubusercontent.com/53333879/215533333-73b3bce7-0b5b-4908-b015-a746c28c3ccf.gif)

**Comment by jackfish0405** [comment]
After another test, I reduced the size of the browser window. When adding nodes, the size of the actual area of ​​the MAP seems to be related to the size of the browser window.
![2](https://user-images.githubusercontent.com/53333879/215538524-a9e3c853-d4ca-4bde-b2a3-ac592622b71f.gif)

**Comment by dream-hunter** [comment]
Ok, i'll try to help a little bit here:
There is the problem in /cacti/include/themes/modern/main.css:
```
html, body {
    height: 100%;
    width: 100%;
    margin: 0px;
    font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
    overflow: hidden;
}
```
The plugin inherit overflow: hidden; and we have the problem with scrolls.

I think the better way is delete the following line in weathermap-cacti-plugin-editor.php:
```
<link rel='stylesheet' type='text/css' media='screen' href='<?php print $config['url_path'] . 'include/themes/' . $selectedTheme . '/main.css';?>' />
```
I tried this way and it works quite fine.

# BUT

There is another problem with adding new nodes. The script takes coordinates, from window position - not real pos. So nodes appears in wrong spots...
(in a big map of course)

**Comment by TheWitness** [comment]
Yea, I know what to do.  Just busy with the day job.  I'll be back at it shortly.

**Comment by TheWitness** [comment]
Okay, I've got this fixed now.  Not you may have to forcibly reset your browsers css and js cache.  There is no zoom to full page on Add node.  Everything just stays at the same zoom level.  That was quite annoying.
