### ISSUE TITLE
There is no option to create a new map。

### ISSUE THREAD

**Issue by jackfish0405** [thurban/plugin_weathermap#75]
There is no option to create a new map. It seems that only new files can be edited in the linux config directory.
previous version of the page：
![image](https://user-images.githubusercontent.com/53333879/215386786-7134d04a-5c06-41ae-a24d-bfcce543ca89.png)

**Comment by TheWitness** [comment]
I have to remove that page.  You add maps from cacti now. Thanks for reminding me.

**Comment by TheWitness** [comment]
This page is no longer in use, but try the new duplicate option from the Management interface.
