### ISSUE TITLE
Graph Selector and Data Source Selector enhancement suggestions.

### ISSUE THREAD

**Issue by jackfish0405** [thurban/plugin_weathermap#76]
If the Graph Selector can be automatically associated with the Data Source and added to the text box together, and the Selector supports regular expressions, it will be more convenient to add a link graph.
![image](https://user-images.githubusercontent.com/53333879/215472178-773529fe-cb2c-49ee-84e2-149a72e3a81c.png)

**Comment by TheWitness** [comment]
Sounds like a feature request, but you statement is a bit ambiguous and a run-on sentence.  Can you be more specific?

**Comment by jackfish0405** [comment]
Sorry, is this description more clear?

**1>Searches will be faster if Graph Selector and Data Source Selector support regular expressions.**

![image](https://user-images.githubusercontent.com/53333879/215492010-e2fa5b91-b4e7-4391-85e1-07011ecba8c8.png)


**2>The search contents of Graph Selector and Data Source Selector are the same, such as RouterA-G1/1, can only add one, and the other will be completed automatically.** 

![image](https://user-images.githubusercontent.com/53333879/215487801-a46a7bbf-3977-4fcb-8f1a-baa660ea1c75.png)
 **Just like the [Pick from Cacti] option in previous versions."Info URL:"and"'Hover' Graph URL:" is added automatically.**

![image](https://user-images.githubusercontent.com/53333879/215490856-4fa107d0-39fa-4af2-a0cc-f3b2fcbc164b.png)

**Comment by TheWitness** [comment]
So, in the old version, augmenting the pick would be automatic.  That's not a big deal.  Howie was discussing that, but I had not idea what he was talking about until you pointed this out visually above.

**Comment by TheWitness** [comment]
Okay, this is fixed now in my personal repo.  Be a part of the next push.
