### ISSUE TITLE
can't remove an icon on a MAP that has special character on the name of the label

### ISSUE THREAD

**Issue by arno-st** [thurban/plugin_weathermap#78]
On the editor of weathermap (console-.>weathermap-> edition of a map
I have a NODE that is juste a label, and I neet to specify ICON NONE

`
NODE DC_Praz-SÃ©chaud
        LABEL DC_Praz-SÃ©chaud
        POSITION 1740 75
`

I got this error when I try to do it:
`
30/01/2023 14:20:56 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/weathermap/weathermap-cacti-plugin-editor.php[173]:setNodeProperties(), /plugins/weathermap/lib/editor.actions.php[314]:WeatherMap->WriteConfig(), /plugins/weathermap/lib/WeatherMap.class.php[3381]:CactiErrorHandler())
30/01/2023 14:20:56 - ERROR PHP NOTICE in Plugin 'weathermap': Undefined property: stdClass::$defined_in in file: /usr/share/cacti/plugins/weathermap/lib/WeatherMap.class.php on line: 3381
30/01/2023 14:20:56 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/weathermap/weathermap-cacti-plugin-editor.php[173]:setNodeProperties(), /plugins/weathermap/lib/editor.actions.php[314]:WeatherMap->WriteConfig(), /plugins/weathermap/lib/WeatherMap.class.php[3380]:CactiErrorHandler())
30/01/2023 14:20:56 - ERROR PHP NOTICE in Plugin 'weathermap': Undefined property: stdClass::$name in file: /usr/share/cacti/plugins/weathermap/lib/WeatherMap.class.php on line: 3380
30/01/2023 14:20:56 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/weathermap/weathermap-cacti-plugin-editor.php[173]:setNodeProperties(), /plugins/weathermap/lib/editor.actions.php[314]:WeatherMap->WriteConfig(), /plugins/weathermap/lib/WeatherMap.class.php[3381]:CactiErrorHandler())
30/01/2023 14:20:56 - ERROR PHP NOTICE in Plugin 'weathermap': Undefined property: stdClass::$defined_in in file: /usr/share/cacti/plugins/weathermap/lib/WeatherMap.class.php on line: 3381
30/01/2023 14:20:56 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/weathermap/weathermap-cacti-plugin-editor.php[173]:setNodeProperties(), /plugins/weathermap/lib/editor.actions.php[314]:WeatherMap->WriteConfig(), /plugins/weathermap/lib/WeatherMap.class.php[3380]:CactiErrorHandler())
30/01/2023 14:20:56 - ERROR PHP NOTICE in Plugin 'weathermap': Undefined property: stdClass::$name in file: /usr/share/cacti/plugins/weathermap/lib/WeatherMap.class.php on line: 3380
30/01/2023 14:20:56 - CMDPHP PHP ERROR WARNING Backtrace: (/plugins/weathermap/weathermap-cacti-plugin-editor.php[173]:setNodeProperties(), /plugins/weathermap/lib/editor.actions.php[294]:CactiErrorHandler())
30/01/2023 14:20:56 - ERROR PHP WARNING in Plugin 'weathermap': Creating default object from empty value in file: /usr/share/cacti/plugins/weathermap/lib/editor.actions.php on line: 294
`

I suspect the error is related to the name of the NODE (the LABEL is the same)
`
NODE DC_Praz-SÃ©chaud
`

And on the edit it shown as 
`DC_Praz-S�chaud`

But the icone is shown as:
`DC_Praz-Séchaud`

It's the only one who give me this error, that's why I'm thinking about the name of the LABEL..
By the way changin tht line 169 of ../lib/editor.inc.php
From `return str_replace($drop_char_match, $drop_char_replace, urldecode($str));`
To `return str_replace($drop_char_match, $drop_char_replace, html_escape($str))`

Didn't solve the issue

**Comment by TheWitness** [comment]
Okay, cool.  There is over-escaping going on.  Just have to find it.

**Comment by TheWitness** [comment]
This is interesting, cause I can use those characters on my version after switching the html_escape().  Also though there is an odd behavior.  If I have a link that is connecting to the node, and I rename the node, the link get's lost.  Is that legacy behavior too?

![InternationalCharacters](https://user-images.githubusercontent.com/1439914/215496866-efc7548b-4661-40f0-9cf0-40d7a07bcbbd.gif)

**Comment by arno-st** [comment]
Yes it's correct, happen also on 0.98a

Because when you do an 'edit' (that let you change the configuration directly on the file), instead of changing the value on the GUI, it's not propagated on every line where your node is used.

When you look at the LINK there is NODES (plural) line that define both end, and that's where the new name is not propagated.

**Comment by arno-st** [comment]
Ho by the way I just try to edit directly the file (clicking on the edit button, and the message that come is:
`# the request item didn't exist. That's probably a bug.`

Instead of the real config I have on the file:
`NODE DC_Praz-SÃ©chaud
        LABEL DC_Praz-SÃ©chaud
        POSITION 1740 75
`

**Comment by TheWitness** [comment]
I am not able to reproduce this.  I've created a WeatherMap file and added and deleted a node.  What I'm suspecting is that your need to change your OS' default language to an international charset so that the config files are not ASCII but UTF8.

One your Servers console, run the `locale` command, all the locales should have a UTF-8 suffix.  See the below.

```
LANG=en_US.UTF-8
LANGUAGE=en_US:en
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```
