### ISSUE TITLE
Bandwith text a bit off with angled style and popup size issues

### ISSUE THREAD

**Issue by nicolatron** [thurban/plugin_weathermap#79]
Sorry not posting before, so busy. Seen this problems.

Before (thurban)
![Captura-2023-01-31 17_18](https://user-images.githubusercontent.com/6955471/215822615-8f3c702d-9180-45d4-8391-e7055cb0e9c4.png)

After
![Captura-2023-01-31 17_17](https://user-images.githubusercontent.com/6955471/215822677-24891ecc-7444-4d77-ac0d-84a74f36cc79.png)

Relevant configuration, I think problem is with links style angled and not horyzontal lines.
```
LINK DEFAULT
        WIDTH 4
        ARROWSTYLE compact
        BWLABEL bits
        BANDWIDTH 1000M
        BWFONT 100
        COMMENTFONT 100
        COMMENTFONTCOLOR 255 0 0
        BWSTYLE angled
        OVERLIBWIDTH 795
        OVERLIBHEIGHT 346
```

I think this have been commented already, the overlib popups are not fit to the image size.

Before (thurban)
![popup_before](https://user-images.githubusercontent.com/6955471/215822777-4debd098-a3ed-4c8d-99b6-36ca87af9986.png)

After
![after_popup](https://user-images.githubusercontent.com/6955471/215822808-d7b3cc79-8681-42ae-868f-ec1b40df1448.png)

Thanks

**Comment by TheWitness** [comment]
Beta 1 or 2 or 3?

**Comment by nicolatron** [comment]
Beta 3 is my guess.

```
weathermap# git log -1
commit cc973c08f7beab4659466c0d03a572b5cc02ca13 (HEAD -> develop, origin/develop, origin/HEAD)
Author: TheWitness <thewitness@cacti.net>
Date:   Sun Jan 29 14:58:40 2023 -0500

    WeatherMaps Beta3 (#73)
    
    * Fixing Issues #52 & #53 - Disabling
    ...
```
Got it via 'git clone https://github.com/Cacti/plugin_weathermap' at 2023-01-31 16:30CET

**Comment by TheWitness** [comment]
Yea, if you want the stuff early, you'll have to get it from my clone of that repo.  I'll be doing work this weekend.

**Comment by TheWitness** [comment]
Interesting, when editing the map is sort of fine, but when rendering it, not so fine.

**Comment by TheWitness** [comment]
I'm wracking my brain on this one.  What version is on your production system?

**Comment by TheWitness** [comment]
Forget about it.  I figured it out in the end.  Should be good now.
