### ISSUE TITLE
Weathermap 1.0 - Editor button leads to the Editor page without css

### ISSUE THREAD

**Issue by MSS970** [thurban/plugin_weathermap#81]
Clicking on the "Editor" button leads to the Editor page without css.
![Editor button](https://user-images.githubusercontent.com/124117691/216049865-29f4f47a-cc0e-46a2-82a1-9b104766c4b9.PNG)
![Editor Page without css](https://user-images.githubusercontent.com/124117691/216049886-0a827c93-caf6-4998-8e46-8f0b4c80c5da.PNG)

**Comment by TheWitness** [comment]
Technically, there is not an Add button, but let me know what you think about how I approached it.  You are better off duplicating from the Management page though.

**Comment by MSS970** [comment]
The weathermap "Edit" and other help links can be enabled using:
Cacti Configuration -> Settings -> Weathermap -> Show Weathermap Help Links
Enable the "Show Weathermap Help Links", then the "Edit" button will be available in the weathermap page at the bottom of the weathermap:
Powered by PHP Weathermap Version 1.0 --- Weathermap Management | Local Documentation | Editor

So I refer to this "Edit" button.

**Comment by MSS970** [comment]
Which I think it should be removed as the access to the Editing page is achieved through:
Management -> Weathermap.
