### ISSUE TITLE
WeatherMap sort order

### ISSUE THREAD

**Issue by jackfish0405** [thurban/plugin_weathermap#87]
Beta 4. 
1> Adjust the order in console->management->weathermaps, and the order of the actual display pages remains unchanged.

2> In console->management->wathermaps, click move map up/down to move one line, and after refreshing, it is found that two lines have been moved.

**Comment by TheWitness** [comment]
So, you need to restart what is wrong more precisely.  The order does work on the management page, so what is wrong now from your perspective.

**Comment by jackfish0405** [comment]
After adjusting the order, the order on this page does not change.
![image](https://user-images.githubusercontent.com/53333879/217136862-5567731a-6460-49c3-8ef0-e749a7b082f1.png)
click move map up/down to move one line, and after refreshing, it is found that two lines have been moved.
![2](https://user-images.githubusercontent.com/53333879/217136720-1ec4b569-d73b-441c-86e4-b72911cf16d7.gif)

**Comment by TheWitness** [comment]
Okay.  In the back end, you sequencing is mangled up with more than one of the maps sharing the same sequence.

We had this at one time in cacti, and we switched the algo.

**Comment by TheWitness** [comment]
I made a few updates to help you diagnose this.

**Comment by jackfish0405** [comment]
So how should I test now? I downloaded your updated version. The sorting is still unsuccessful. It seems that no matter how the value of Order changes, the value of ID is always used to sort.
![image](https://user-images.githubusercontent.com/53333879/217811865-df136181-e235-46a6-b335-5b6babc027c9.png)
![image](https://user-images.githubusercontent.com/53333879/217811933-5c358234-d543-4e7f-ac7d-c7034a761a61.png)

**Comment by TheWitness** [comment]
It looks like the sorting is correct on the Management page, but not good on the Top Tab Weathermap page.

**Comment by TheWitness** [comment]
Okay, fixed now.
