### ISSUE TITLE
Add new node position problem.

### ISSUE THREAD

**Issue by jackfish0405** [thurban/plugin_weathermap#88]
Beta 4.
When Weathermap Editor adds a new node, the location coordinates can only be displayed up to the size of the browser window, not the actual pixel size set by the map.
![image](https://user-images.githubusercontent.com/53333879/217132638-0539e8d4-f155-4e75-a64d-9bb042a4d535.png)
![1](https://user-images.githubusercontent.com/53333879/217132664-766109bb-a448-4562-a746-93eed62fcf7f.gif)

**Comment by TheWitness** [comment]
I made a change on this tonight.
