### ISSUE TITLE
Allow more Graphs types to be searched for

### ISSUE THREAD

**Issue by dream-hunter** [thurban/plugin_weathermap#89]
There is unable to apply some graphs on hosts except interface statistics. It looks like the nodes works by the same way as links.

**Comment by TheWitness** [comment]
Ah, you want non-interface graphs on Nodes?

**Comment by dream-hunter** [comment]
Sure. This feature was able before.

**Comment by TheWitness** [comment]
This is now resolved.

**Comment by TheWitness** [comment]
Resolved here: https://github.com/Cacti/plugin_weathermap/commit/350b4a311f657754b40905bf7d50a8f4a7e259fe
