### ISSUE TITLE
Error: You have an error in your SQL syntax, Mysql 8.0 Weathermap 1.0 

### ISSUE THREAD

**Issue by alexvides2002** [thurban/plugin_weathermap#90]
Hi! 

I have a problem with the "weathermap" plugin. The permissions on the maps in cacti appear as "NO USERS" and it does not allow them to be edited. The log shows me the following message:

 CMDPHP ERROR: A DB Row Failed!, Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'groups FROM weathermap_auth WHERE mapid = '21' HAVING special > 0 OR users > 0 O' at line 1

I have mysql 8.0, and cacti 1.2.23. there seems to be some error in the way the query is structured in this version in the weathermap-cacti-plugin-mgmt.php file , will there be any changes for this version in mysql? I'm not very good with SQL queries. 

Thanks a lot!

**Comment by TheWitness** [comment]
Looks like they keep adding more reserved words.  Should be all set now.

**Comment by alexvides2002** [comment]
Great! it worked. The allowed users already appear in the "Accessible by" option, but when editing the map, for example, adding a node, simply does nothing, is any additional library required for this to work? I thought that with the permissions it would be solved, and the log does not show any error. Thank you very much if you can guide me.

**Comment by alexvides2002** [comment]
I tried today and I was able to edit the map, thank you very much for the support

**Comment by mykola379** [comment]
Good day. Sorry for my English. This is the problem - in one of the maps I add rights to the test user, after that this user becomes absent in other maps. This applies to LDAP and local users. However, the Admin user is present in all maps - regardless of what rights he has to the map. Help solve the problem. Thank you.
Cacti 1.2.23 + Weatherm
![map1](https://user-images.githubusercontent.com/126241282/221215217-1d4a7485-e7e0-4e8a-a968-dd8faa36deee.png)
ap 1.0 Beta 4
![map2](https://user-images.githubusercontent.com/126241282/221215258-ccab92a4-8472-4850-a931-b00c642aff54.png)

**Comment by TheWitness** [comment]
Can you create a screen2gif animation and upload it?  It should show the process.

**Comment by TheWitness** [comment]
Also, please create a new issue.

**Comment by mykola379** [comment]
Thanks for the answer. I am sending a gif animation.
![Animation](https://user-images.githubusercontent.com/126241282/221220527-3d9b922e-0f3b-42d6-b557-a2a314685bec.gif)
