### ISSUE TITLE
User permission issues

### ISSUE THREAD

**Issue by TheWitness** [thurban/plugin_weathermap#96]
Good day. Sorry for my English. This is the problem - in one of the maps I add rights to the test user, after that this user becomes absent in other maps. This applies to LDAP and local users. However, the Admin user is present in all maps - regardless of what rights he has to the map. Help solve the problem. Thank you.
Cacti 1.2.23 + Weathermap 1.0 Beta 4

_Originally posted by @mykola379 in https://github.com/Cacti/plugin_weathermap/issues/90#issuecomment-1443547729_

**Comment by mykola379** [comment]
Thanks for the answer. I am sending a gif animation. Cacti 1.2.23 | Weathermap 1.0 Beta 4 | Mariadb 10.8.5
![Animation](https://user-images.githubusercontent.com/126241282/221221693-c82b20c3-b7c6-4c89-bc17-c8fc607ddd0c.gif)

**Comment by TheWitness** [comment]
Okay, issue is clear now.
